# Generated by Django 5.1.4 on 2025-02-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=2000)),
                ('recipe_description', models.CharField(max_length=200000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
