# Generated by Django 5.1.4 on 2025-02-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=2000)),
                ('confirm_password', models.CharField(max_length=2000)),
            ],
        ),
    ]
